/*　システムログ */
CREATE TABLE IF NOT EXISTS SYSTEM_LOG (
	LOG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	USER_ID BIGINT comment 'ログ記録時のユーザID 0はユーザ無しでシステムが実行した処理のログ',
	COMPANY_ID BIGINT default 0 comment 'COMPANIES::COMPANY_ID 0は企業無しでシステムが実行した処理のログ',
	LOG_TYPE INT NOT NULL comment 'ログの種類 1:INFO 2:WARNING 3:ERROR',
	LOG_MESSAGE TEXT comment 'ログメッセージ 改行は\n',
	INSERT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
	INDEX idx_user_id (USER_ID)
);

-- パーティション
ALTER TABLE SYSTEM_LOG PARTITION BY RANGE (YEAR(INSERT_TIME)) (
	PARTITION y2026 VALUES LESS THAN (2026)
);
INSERT INTO PARTITION_TABLE (TABLE_NAME, PARTITION_TYPE, LAST_EXCUTED_YEAR) VALUES ('SYSTEM_LOG', 1, 2025);

/* アクティビティログ */
CREATE TABLE ACTIVITY_TYPE (
	ACTIVITY_TYPE_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'アクティビティタイプの識別子',
	TYPE_NAME VARCHAR(50) NOT NULL COMMENT 'アクティビティタイプの名前'
) COMMENT='アクティビティタイプを管理するテーブル';

CREATE TABLE USER_ACTIVITY (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '一意の識別子',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'ユーザの識別子',
    GROUP_ID BIGINT UNSIGNED DEFAULT 0 COMMENT 'グループの識別子 0はグループ無し',
    ACTIVITY_TYPE_ID INT UNSIGNED NOT NULL COMMENT 'アクティビティタイプの識別子 ACTIVITY_TYPE::ACTIVITY_TYPE_ID',
    ACTIVITY_DETAIL TEXT COMMENT 'アクティビティの詳細 改行は\n',
    INSERT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'アクティビティの日時',
    FOREIGN KEY (ACTIVITY_TYPE_ID) REFERENCES ACTIVITY_TYPE(ACTIVITY_TYPE_ID),
	FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`) ON DELETE CASCADE,
    INDEX idx_user_id (USER_ID),
    INDEX idx_group_id (GROUP_ID)
) COMMENT='ユーザのアクティビティを記録するテーブル';

-- パーティション
ALTER TABLE USER_ACTIVITY PARTITION BY RANGE ((YEAR(INSERT_TIME)*100 + MONTH(INSERT_TIME))) (
	PARTITION m202501 VALUES LESS THAN (202501),
	PARTITION m202502 VALUES LESS THAN (202502),
	PARTITION m202503 VALUES LESS THAN (202503),
	PARTITION m202504 VALUES LESS THAN (202504),
	PARTITION m202505 VALUES LESS THAN (202505),
	PARTITION m202506 VALUES LESS THAN (202506),
	PARTITION m202507 VALUES LESS THAN (202507),
	PARTITION m202508 VALUES LESS THAN (202508),
	PARTITION m202509 VALUES LESS THAN (202509),
	PARTITION m202510 VALUES LESS THAN (202510),
	PARTITION m202511 VALUES LESS THAN (202511),
	PARTITION m202512 VALUES LESS THAN (202512),
);

INSERT INTO PARTITION_TABLE (TABLE_NAME, PARTITION_TYPE, LAST_EXCUTED_YEAR) VALUES ('SYSTEM_LOG', 1, 2025);

